# Generated by Django 5.0.3 on 2024-05-09 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('write_date', models.DateTimeField()),
                ('sender_place', models.TextField()),
                ('sender_post_num', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('reciever_place', models.TextField()),
                ('reciever_post_num', models.IntegerField()),
                ('reciever', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
