# Generated by Django 5.0.3 on 2024-04-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('writer', models.CharField(max_length=20)),
                ('write_date', models.DateTimeField()),
                ('sender_place', models.TextField()),
                ('sender_post_num', models.IntegerField()),
                ('reciever_place', models.TextField()),
                ('reciever_post_num', models.IntegerField()),
                ('reciever', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=20)),
            ],
        ),
    ]
