# Generated by Django 5.0.3 on 2024-05-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='write_date',
        ),
    ]
